server:
  port: 9090
spring:
  application:
    name: 241dswspringmsCourse
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://137.184.120.127:5432/coursesDb
    username: modulo4
    password: modulo4
  jpa:
    hibernate:
      ddl-auto: none
    #database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect      
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka