server:
  port: 8761

spring:
  application:
    name: 241dswspringmsEureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: http://localhost:${server.port}/eureka/
